apiVersion: ENC[AES256_GCM,data:pRc=,iv:wy7uUPzQHiN/Ry9TrEPpv7X8W6l0DPMhrYPNnMl22UM=,tag:K3AuPC5gQz6yDS6Ldpejxw==,type:str]
kind: ENC[AES256_GCM,data:A98Bln3q,iv:sDzIIFXpTLzMLoUZ//ClqUm4yMBCdlJyn3WN8BC94ZQ=,tag:CS9Ze/rEzMs/tI9yGqhzIw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PbM7RHMgsRRTxuGqieyl,iv:BU4ibO8AslFo9Y/vJ8ldOZzqOiFBViC++N4Gc/WZ44E=,tag:q7pwoQJPzjfgo4hXu0mrNQ==,type:str]
    namespace: ENC[AES256_GCM,data:11pnrSc/6Q==,iv:P0K1HGok9ApckkqGMoLQEHgBFFBSLf5tYh/3EoyP4Yg=,tag:4ZKRvrCCO7nOFw+QSvqhig==,type:str]
    labels:
        degree: ENC[AES256_GCM,data:enB1,iv:oxRw+nN48jm0kDj0LBntWc3dT0u2f0n3ngfV8qm2bsU=,tag:MefnUhfpvxkL2c1TJi8wow==,type:str]
        version: ENC[AES256_GCM,data:GzI=,iv:JtV8NMOheOSFvv6TZf4qV7zH8K+0V09Kasm+yRUXmT8=,tag:zIdLgInsAVtm0uf6/HsGzA==,type:str]
type: ENC[AES256_GCM,data:NXoaVcjJ,iv:H+mRXxx81CEGXlzuYdWrkuZxciEgWtkWuo7OdQRRCtI=,tag:fsetxUEkVpf9WA4IBsUdDQ==,type:str]
data:
    POSTGRES_USER: ENC[AES256_GCM,data:guKQzIWB9p1u8LirjPAYV7hK1Y0Jf5f0/XVh5me+NBSnHBtMzqxrmA==,iv:vuKuSGnVjjaXXtqhgYZg0s1NepEHYF93QMJC1avY6iQ=,tag:oO7pMhDxpZBuqq1UeRfgUA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gAp9+xivwNlCzRWQ6VQ2hKUM+Uo9HFqi+RUV4hY2KTEbo/m43WApFfNz9NfZk82TQd9QhSqYbRhjfp+YHYqRig==,iv:k/tMyPLZW6Mv9egZboNaB08V2Ll+EWoMUqTHQxJ5V3M=,tag:JcjF5AfQ8s5VIt6xezKVQQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:EGO43NN3/05dtkBz27WQAg==,iv:nIyqZm3WOUhliQeQ8T+Lui5CuhsjLHLnjpJOwAL+iCk=,tag:arO6Z4iDVcu7lnLfWyPwIA==,type:str]
    POSTGRES_JDBC: ENC[AES256_GCM,data:WIDbsgMSoxXnxL5/7hDRUHeE1/2NZ3xtZ2+QYRRyllxdfEoyAf7/7Z3WH54Don0yW1Wsuayk1CDpcjYQlimodE+qqWM=,iv:HFxK+ckOjnqEr12TkpJieI3s8WcmRJTfOqwgZMug6Sc=,tag:kNPczYkven3wmDB6Cog2Rw==,type:str]
    ELASTIC_PASSWORD: ENC[AES256_GCM,data:UfPFRZExhAtibxKv+h2bsr11cv6kjLN5U9HIqa/kaKUdaKhgh5GzQUNyLE4XSHyuJNUxPiLBRNppJSH9,iv:q00iHVVaUkk0FbXd/cfHssfDb7s2d6tmSayb071DDU4=,tag:NIVS1DR+ElmEF5ua3z5Vxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-15T19:27:43Z"
    mac: ENC[AES256_GCM,data:nBjy2rKGozWJf/9v+zRWlaFBWmJy3fVxIVohoJmWViSYhUHnMl1H5u5TKQ00563F1pYnPDuNztXEjpy/hfk2zXX85qTnnw8e2PdO5DERzZ7Mfx6DdnGRd8rWSAdffN0aLyV5eAE16Ec1Kj2JFJCWHiwUrJt13f89XgkLaDbFyIg=,iv:BvB1KtpTTr4ZTKwBdh36z4Ie9Yd0iZy3EcPArdCPfqM=,tag:PsLBKssfRDGJntRqIae0Hw==,type:str]
    pgp:
        - created_at: "2024-12-15T19:27:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DFi21Y51QjF0SAQdAhroI1aTVJYDxgiyOF8P1VjpxqGSeP12sUBntdnkSkjsw
            zTJsC5VOwd6r1CEyvrCJWGxBoMKiO3AaCoLGtJtuzJ48jTeUZPzuywXnLvKOIZKz
            1GgBCQIQjDFofFh3LVzTVd77J/wecTzbzRqW85xTh1m9h2+0T/wUUgPaP+ov6rJi
            Q7Q5JBpZpU13wdNCOYs9JaXVLe5x3l9xk404cubVrqkZv+Axw6ocaHBX9Sf/2XAr
            D1GVG48xG7y5pw==
            =hajI
            -----END PGP MESSAGE-----
          fp: C648648FE6DBB10C10194C69BFC7DFFD44BBE4AE
    unencrypted_suffix: _unencrypted
    version: 3.9.2
