apiVersion: v1
kind: Service
metadata:
  name: tuvarna-service
  namespace: tuvarna
  labels:
    degree: phd
    version: v1

spec:
  # type: LoadBalancer
  type: NodePort

  selector:
    degree: phd
    type: database
    version: v1

  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 30000

    - name: client
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30001

    - name: server
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30002
